Blinky.c
APP_MAIN_STK_SZ
uint64_t app_main_stk[(512U)/8][(512U)/8]
const osThreadAttr_t app_main_attr
Referenced by main.
volatile uint32_t delay_val
Referenced by thrBUT.
osThreadId_t tid_thrLED
Referenced by app_main, thrBUT.
osThreadId_t tid_thrBUT
Referenced by app_main.
static __NO_RETURN void thrLED(void *argument)
Referenced by app_main.
static __NO_RETURN void thrBUT(void *argument)
References delay_val, tid_thrLED.
Referenced by app_main.
__NO_RETURN void app_main(void *argument)
File Name : main.hpp Description : This file contains the common defines of the application.
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners. COPYRIGHT(c) 2018 STMicroelectronics Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. Uncomment the line below to expanse the "assert_param" macro in the HAL drivers code
References thrBUT, thrLED, tid_thrBUT, tid_thrLED.
Referenced by main.