main.c
void SystemClock_Config(void)
File Name : main.c Description : Main program body.
System Clock Configuration. This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners. COPYRIGHT(c) 2018 STMicroelectronics Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
References _Error_Handler.
Referenced by main.
static void MX_GPIO_Init(void)
Configure pins as Analog Input Output EVENT_OUT EXTI.
Referenced by main.
uint32_t HAL_GetTick(void)
Override default HAL_GetTick function.
References SystemCoreClock.
HAL_StatusTypeDef HAL_InitTick(uint32_t TickPriority)
Override default HAL_InitTick function.
int main(void)
References app_main, app_main_attr, MX_GPIO_Init, SystemClock_Config, SystemCoreClockUpdate.
void _Error_Handler(char *file, int line)
This function is executed in case of error occurrence.
File Name : stm32l0xx_hal_msp.c Description : This file provides code for the MSP Initialization and de-Initialization codes. None None
Referenced by SystemClock_Config.